### ISSUE TITLE
Manage Journey: Date selection

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#14]
CAnnot select date time here:

![image](https://cloud.githubusercontent.com/assets/1998630/9022295/2e12bb7c-3868-11e5-8137-e10408229f14.png)

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
Cannot open date selector here:
![image](https://cloud.githubusercontent.com/assets/1998630/9067643/a7d69d78-3ad6-11e5-82ff-00f1f0491e65.png)

**Comment by frabbibd** [comment]
This is fixed. Please check.

**Comment by bluedoorsoftware** [comment]
Closing
