### ISSUE TITLE
Weclome page: responsive

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#19]
When shown on small screen maybe we should not show text in black? Only title?

![image](https://cloud.githubusercontent.com/assets/1998630/9022373/90ea9132-386a-11e5-8cad-d393c7866b80.png)

**Comment by frabbibd** [comment]
Done, please check.

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
![image](https://cloud.githubusercontent.com/assets/1998630/9045917/0dd63f60-3a1f-11e5-8b66-350441d76f85.png)

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Not fixed
=======

**Comment by frabbibd** [comment]
Hi, this is fixed the section you marked as red color is not the text. The "Online Library" is the text which is with the image. Please check again then you will be clear. All square box text are hidden in small screen.

**Comment by bluedoorsoftware** [comment]
Yes, my error. This is fixed. Closing
