### ISSUE TITLE
Format all dates in all kendo grids in uk format: dd/mm/yyyy

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#26]
![image](https://cloud.githubusercontent.com/assets/1998630/9032310/20c5666a-39b5-11e5-934d-c92da05fcef0.png)

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
Example of bug -
![image](https://cloud.githubusercontent.com/assets/1998630/9067632/8656bfd4-3ad6-11e5-8edb-f0df5c4d9066.png)

**Comment by frabbibd** [comment]
Please check. Date format is fixed.

**Comment by bluedoorsoftware** [comment]
Verified. Closing
