### ISSUE TITLE
Manage Journey screen: typos

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#27]
Change to "s" not "S"

![image](https://cloud.githubusercontent.com/assets/1998630/9032346/99628878-39b5-11e5-84a0-e311ec742c67.png)

and "journey with [organisation name]" not "Journey"

![image](https://cloud.githubusercontent.com/assets/1998630/9032372/e8173e5a-39b5-11e5-81b9-c7ed4a36c46d.png)

[organisation name] is the value from  dbo.USERS.USER_ORGANISATION_NAME

**Comment by frabbibd** [comment]
Done, please check.

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
![image](https://cloud.githubusercontent.com/assets/1998630/9108933/9b9bde02-3c29-11e5-9189-5a5b6281efab.png)

**Comment by frabbibd** [comment]
New UI is implemented. So this bug still valid?

**Comment by bluedoorsoftware** [comment]
No - closing
