### ISSUE TITLE
Referrals: Add button

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#5]
Get this when try to add a referral:

![image](https://cloud.githubusercontent.com/assets/1998630/9022228/734d013c-3865-11e5-9d9b-360bec9a275c.png)

**Comment by frabbibd** [comment]
Fixed. Please check.

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
Needs to display add new Referral window as the SL demo.

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Not complete
==========
Drop lists need data from SQL tables in cwconline. This is just one example:
![image](https://cloud.githubusercontent.com/assets/1998630/9067547/07c41950-3ad6-11e5-8231-d5897fa7bd5c.png)

please check all droplists on all tabs

**Comment by frabbibd** [comment]
Drop down list is filled with data now. Please check.
