### ISSUE TITLE
Referrals: Message box

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#8]
Can we have nicer looking message box?

![image](https://cloud.githubusercontent.com/assets/1998630/9022237/f9409100-3865-11e5-9ecf-5ebbb2264082.png)

**Comment by frabbibd** [comment]
Please check.

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
 I cannot see the changed function

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
poor ui -
![image](https://cloud.githubusercontent.com/assets/1998630/9067470/8eb8c29a-3ad5-11e5-8801-7c5ef6d16b59.png)

**Comment by frabbibd** [comment]
Please check now. The alert UI has changed.

**Comment by bluedoorsoftware** [comment]
Verified. Closing
