### ISSUE TITLE
Minor text changes

### ISSUE THREAD

**Issue by bluedoorsoftware** [bluedoorsoftware/CWCOnlineKendo#9]
![image](https://cloud.githubusercontent.com/assets/1998630/9022241/19c15a5e-3866-11e5-9fdc-c5a335ac1976.png)

**Comment by frabbibd** [comment]
Please check.

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
![image](https://cloud.githubusercontent.com/assets/1998630/9045883/bf37538a-3a1e-11e5-99fd-cab818463190.png)

**Comment by frabbibd** [comment]
Done. Please check

**Comment by bluedoorsoftware** [comment]
Not fixed
=======
Edits I want are in my first comment, and repeated again here:
![image](https://cloud.githubusercontent.com/assets/1998630/9067503/c61a733c-3ad5-11e5-82bc-6c841016158e.png)

**Comment by frabbibd** [comment]
Please check. Hope this is fixed now in all pages.

**Comment by bluedoorsoftware** [comment]
Closing
